name: Update Nebraska Events GPX

on:
  schedule:
    - cron: "0 11 * * *" # 6am US Central (UTC-5/UTC-6 depending on DST; UTC 11:00 is 6am CST, 5am CDT)
  workflow_dispatch:

jobs:
  update-gpx:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download zip file
        run: |
          # REQUEST_HEADERS should be in curl format, e.g. -H "Cookie: xxx" -H "User-Agent: yyy"
          curl \
            ${{ secrets.GEO_PQ_REQUEST_HEADERS }} \
            -L -o events.zip \
            "https://www.geocaching.com/pocket/downloadpq.ashx?g=${{ secrets.GEO_PQ_NE_EVENTS_ID }}&src=web"

      - name: Extract GPX file
        run: |
          unzip events.zip
          rm -f *-wpts.gpx
          mv *nebraska_events.gpx 'data/$nebraska_events.gpx'

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'Nebotska'
          git config --global user.email 'nebotska@nebraskache.com'
          git add 'data/$nebraska_events.gpx'
          if ! git diff --cached --quiet; then
            git commit -m 'Update published event listing'
            git push
          fi
